name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    name: "Build and upload to GH Pages"
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Workflow Runs
        uses: n1hility/cancel-previous-runs@v2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: "15.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm run build --if-present
        env:
          CANONICAL_URL: "https://instantchocolate.octonezd.me"
          VUE_APP_API_URL: "https://instantchocolate.octonezd.me/instantchocolate.apigen/"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "./dist"
          force_orphan: true
          cname: "instantchocolate.octonezd.me"
