on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-20.04
        name: Build and deploy to GitHub Pages
        steps:
            - name: Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.7.0
              with:
                  access_token: ${{ github.token }}
            - uses: actions/checkout@master
              with:
                  fetch-depth: 0
            - name: Install Node
              run: |
                  curl -fsSL https://deb.nodesource.com/setup_15.x | sudo -E bash -
                  sudo apt-get install -y nodejs
            - run: npm ci
            - run: npm run build
              env:
                  VUE_APP_API_URL: https://api-instantchocolate.octonezd.me/
                  CANONICAL_URL: https://instantchocolate.octonezd.me
                  INSTALLER_REPOSITORY: "OctoNezd/instantchocolate.installer"
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
                  cname: instantchocolate.octonezd.me
                  force_orphan: true
